### ISSUE TITLE
app name bug

### ISSUE THREAD

**Issue by ghamha1n** [usecanvas/ember-electron#2]
Good day all,

when i change app name, app throw me error

```
10:23:55 AM ember.1 |  version: 0.2.5
10:23:55 AM ember.1 |  A new version of ember-cli is available (1.13.7). To install it, type ember update.
10:23:57 AM ember.1 |  Livereload server on port 36529
10:23:57 AM ember.1 |  Serving on http://localhost:5000/
10:23:57 AM electron.1 |  events.js:85
10:23:57 AM electron.1 |        throw er; // Unhandled 'error' event
10:23:57 AM electron.1 |              ^
10:23:57 AM electron.1 |  Error: spawn /Users/hamzah/Desktop/ember-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/…
10:23:57 AM electron.1 |      at exports._errnoException (util.js:746:11)
10:23:57 AM electron.1 |      at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
10:23:57 AM electron.1 |      at child_process.js:1144:20
10:23:57 AM electron.1 |      at process._tickCallback (node.js:355:11)
10:23:57 AM electron.1 |      at Function.Module.runMain (module.js:503:11)
10:23:57 AM electron.1 |      at startup (node.js:129:16)
10:23:57 AM electron.1 |      at node.js:814:3
[DONE] Killing all processes with signal  null
10:23:57 AM electron.1 Exited Abnormally
10:23:57 AM ember.1 Exited Abnormally

```

**Comment by jclem** [comment]
Hey @ghamha1n we don't actually maintain this, it was just an investigation. If there's a bug here you can fix, though, I'd happily accept a PR.
